### ISSUE TITLE
[Mobile] Overall site issues

### ISSUE THREAD

**Issue by KennethAshley** [MARKETProtocol/website#193]
### User Story
- [ ] As a user, I want to see the mobile header menu above the content. (fix z-index)

Example:
![image](https://cdn.discordapp.com/attachments/424805354547970049/466083662052720670/image.png)

- [ ] As a user, I don't want to see the "Try out our demo dApp" button above the header.
Example:

![image](https://cdn.discordapp.com/attachments/424805354547970049/466083676028141569/image.png)

- [ ] As a user, I want to see the mobile header above the content. (fix z-index)

Example
![image](https://cdn.discordapp.com/attachments/424805354547970049/466083687713210369/image.png)

- [ ] As a user, I do not want to see the "Join our Newsletter" button above the header
![image](https://cdn.discordapp.com/attachments/424805354547970049/466083715433627668/image.png)

### Why Is this Needed?
These issues need to be fixed so users can preform basic actions like navigating the page and reading copy.

### Description
Type: Bugs! Yuck!

### Reproduction
Load develop branch (right @pelsasser ?) on mobile

### Solution
Seems like most of these issues are `z-index` related and or spacing issues.

### Definition of Done
Elements should be laid out consistently and not over important elements like the header

### Additional Information
@pelsasser I hope the descriptions above outlines the issues properly!

### Todo
- [x]  Remove hero graphic

**Comment by pelsasser** [comment]
> Load develop branch (right @pelsasser ?) on mobile

yes

Interestingly - http://dev.website.marketprotocol.io/ looks more or less fine right now on my browser at a mobile width.  I will test from my phone and report back

**Comment by pelsasser** [comment]
same issues with http://dev.website.marketprotocol.io/  when viewed on an iphone.
