### ISSUE TITLE
[Meta] add meta tags / cards for all social media 

### ISSUE THREAD

**Issue by pelsasser** [MARKETProtocol/website#40]
### User Story

When sharing the website we would like to customize the meta card that is display to twitter, telegram, medium, etc. 

### Why Is this Needed?

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*: should allow for a nice quick summary to the site.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Current Behavior
[comment]: # (Describe what actually happened.)
Our old site card is displayed with our old branding

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
New logo displayed with updated tagline of "Powering safe, solvent and trustless trading of any asset."

### Reproduction
https://cards-dev.twitter.com/validator is the easiest place I know to see it rendered.

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

- [ ] Tags added for twitter
- [ ] Tags added for google+
- [ ] Tags added for Open Graph
- [ ] Any other tags that would heflpul

### Additional Information
https://cards-dev.twitter.com/validator can be helpful
https://moz.com/blog/meta-data-templates-123 is also a great resource

## Before you `start work`
If you have ongoing work from other bounties with us where funding has not been released, please do not pick up a new issue.  We would like to involve as many contributors as possible and parallelize the work flow as much as possible.

Please also note that in order for work to be accepted, all code must be accompanied by test cases as well.

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 0.08 ETH (54.46 USD @ $680.72/ETH) attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/MARKETProtocol/website/40/340).
 * Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
 * $8,157.1 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Started** 3. Submitted 4. Done 

<hr>

__Work has been started__.

 1. [@tschoffelen](https://gitcoin.co/profile/tschoffelen) 

 has committed to working on this project to be completed 6 days, 22 hours from now.

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. Started 3. **Submitted** 4. Done 

<hr>

__Work for 0.08 ETH (54.49 USD @ $681.11/ETH) has been submitted by__: 
 1. 
 1. [@tschoffelen](https://gitcoin.co/profile/tschoffelen) 

 

@pelsasser please take a look at the submitted work:
* [PR](https://github.com/MARKETProtocol/website/pull/42) by @tschoffelen
 

 * Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/MARKETProtocol/website/40/340)
 *  * Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
$8,126.16 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by eswarasai** [comment]
@pelsasser -- Is this good be paid out and closed?

**Comment by pelsasser** [comment]
@tschoffelen - thanks for the quick turnaround, looks like it is all working from our end.

Can you help me understand the choice of a .jpg vs .png for the social.jpg?  

@eswarasai - I will get the bounty paid out now.

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. Started 3. Submitted 4. **Done** 

<hr>

__The funding of 0.08 ETH (53.75 USD @ $671.9/ETH) attached to this issue has been approved & issued to @tschoffelen.__  

 * Learn more at [on the Gitcoin Issue Details page](https://gitcoin.co/issue/MARKETProtocol/website/40/340)
 * Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
 * $7,969.45 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by tschoffelen** [comment]
@pelsasser Facebook's compression algorithm usually causes PNGs with solid backgrounds to look really terrible in my experience. That's the only reason I went for JPG, because otherwise PNG would indeed be the obvious choice for this image.

**Comment by weberV** [comment]
Issue Status: 1. Open 2. Started 3. Submitted 4. **Done** 

<hr>

__This issue now has a funding of 0.08 ETH (55.37 USD @ $692.1/ETH) attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](http://localhost:8000/issue/MARKETProtocol/website/40/340).
 * Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
 * $9,677.96 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)
